{
 "title": "DSA: Algorithm Dashboard",
 "tags": [
  "DSA",
  "Algorithm Dashboard"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Algorithm Throughput (Ops/Sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(dsa_algorithm_executions_ops_total[1m])) by (algorithm_code)",
     "legendFormat": "{{__name__}} - {{algorithm_code}}"
    }
   ]
  },
  {
   "title": "Algorithm P95 Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(histogram_quantile(0.95, sum(rate(dsa_algorithm_duration_ms_milliseconds_bucket[1m])) by (le, algorithm_code)) unless sum(rate(dsa_algorithm_duration_ms_milliseconds_bucket{le=\"+Inf\"}[1m])) by (algorithm_code) == 0) or (sum(rate(dsa_algorithm_duration_ms_milliseconds_bucket{le=\"+Inf\"}[1m])) by (algorithm_code) * 0)",
     "legendFormat": "{{__name__}} - {{algorithm_code}}"
    }
   ]
  },
  {
   "title": "Algorithm Error Rate %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(sum(rate(dsa_algorithm_executions_ops_total{status=\"error\"}[1m])) by (algorithm_code) or (sum(rate(dsa_algorithm_executions_ops_total[1m])) by (algorithm_code) * 0)) / (sum(rate(dsa_algorithm_executions_ops_total[1m])) by (algorithm_code)) * 100",
     "legendFormat": "Error Rate - {{algorithm_code}}"
    }
   ]
  }
 ]
}